/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.kumru;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        JavaLoggingApp classUnderTest = new JavaLoggingApp();
        assertNotNull("app should have a greeting", "hadi gec cnm");
    }
}
